vertx:
  sockjs:
    bridge_options:
      inbound_permitteds:
        - address: /chat/token
        - address: /chat/message
        - address_regex: \/chat\/message\\..+
      outbound_permitteds:
        - address: /chat/token
        - address_regex: \/chat\/message\\..+
  web:
    server_options:
      port: ${server.port:8080}
    static:
      caching_enabled: true
auth0:
  domain: dianw.au.auth0.com
  client-id: mUmPv7JrMurLtgWFsFsOt776ztD43jJB
  client-secret: xlYBdfTdOux5UGiihinS0NYL32q3TotZFfh_w5V29eu7zjiFZ0x8YPBbhrppv93a